version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 10 && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    restart: always
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
